server:
  port: 8761

spring:
  application:
    name: @project.name@

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false

logging:
  file:
    name: logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 5MB
  level:
    root: info
